apiVersion: v1
kind: Service
metadata:
  name: ui-quack
spec:
  selector:
    app: ui-quack
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-quack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-quack
  template:
    metadata:
      labels:
        app: ui-quack
    spec:
      containers:
        - name: ui-quack
          image: gcr.io/daisyduck-reborn/ui-quack:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
