steps:
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '--build-arg','PROFILE=staging',
   '-t', 
   'gcr.io/daisyduck-reborn/ui-quack:${COMMIT_SHA}',   
   '-t', 
   'gcr.io/daisyduck-reborn/ui-quack:latest',
   '.'
  ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'config/stag/application.deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'ui-quack', 
   'ui-quack=gcr.io/daisyduck-reborn/ui-quack:${COMMIT_SHA}'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
images: [
   'gcr.io/daisyduck-reborn/ui-quack:${COMMIT_SHA}',
   'gcr.io/daisyduck-reborn/ui-quack:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY