apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: quack-ui
build:
  artifacts:
    - image: ui-quack
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PROFILE: development
manifests:
  rawYaml:
    - config/dev/application.deployment.yaml
