apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: quack-ui
build:
  artifacts:
    - image: gcr.io/daisyduck-reborn/ui
      docker:
        dockerfile: Dockerfile
        buildArgs:
          PROFILE: dev
manifests:
  rawYaml:
    - config/dev/application.deployment.yaml
deploy:
  kubectl: {}
profiles:
  - name: staging
    build:
      googleCloudBuild: 
        projectId: daisyduck-reborn
      artifacts:
      - image: gcr.io/daisyduck-reborn/ui
        docker:
          dockerfile: Dockerfile
    manifests:
      rawYaml:
      - config/stag/application.deployment.yaml
    deploy:
      kubectl: {}